# Generated by Django 3.2 on 2021-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
