# Generated by Django 3.2 on 2021-05-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0003_alter_listing_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('coins', models.IntegerField(default=0)),
                ('first_time_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_owner',
            new_name='owner',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
