# Generated by Django 3.2 on 2021-05-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210503_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_time_user',
            new_name='first_time',
        ),
    ]
