# Generated by Django 3.2 on 2021-05-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210504_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='card_listed',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.listing'),
        ),
    ]
