# Generated by Django 3.2 on 2021-05-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210504_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidded_by',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='card_listed',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='sold_by',
            new_name='lister',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
    ]
