# Generated by Django 3.2 on 2021-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210509_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
