# Generated by Django 3.2 on 2021-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
